version: '3'
services:
  onboarding-microservice-backend:
    image: proflo/onboarding-microservice-backend
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      mongo_db: "mongodb://onboarding-microservice-db:27017"
      database: "Userscollection"
  onboarding-microservice-db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
volumes:
  db: